import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.9

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 19.0

#[env]
#TERM = "xterm-256color"
